openapi: 3.0.1
info:
  title: Data Records API
  version: 1.0.0
paths:
  /api/data-records:
    post:
      summary: Create a data record
      operationId: createDataRecord
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDataRecordRequest'
      responses:
        '200':
          description: Data record created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDataRecordResponse'
    get:
      summary: Process a data record
      operationId: processDataRecord
      responses:
        '204':
          description: No content (no records to process)
        '200':
          description: Processed data record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessedRecord'

  /api/data-records/report:
    get:
      summary: Get data record report
      operationId: getDataRecordReport
      parameters:
        - name: onlyProcessedRecords
          in: query
          schema:
            type: boolean
          required: false
      responses:
        '200':
          description: Data record report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDataRecordReport'

  /api/data-records/process-configuration:
    get:
      summary: Get data record process configuration
      operationId: getDataRecordProcessConfig
      responses:
        '200':
          description: Data record process configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProcessConfigResponse'
    put:
      summary: Update data record process configuration
      operationId: updateDataRecordProcessConfig
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProcessConfigRequest'
      responses:
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '204':
          description: No content (successfully updated)

components:
  schemas:
    CreateDataRecordRequest:
      type: object
      properties:
        name:
          type: string
        phoneNumber:
          type: string
        amount:
          type: number
          format: decimal
    CreateDataRecordResponse:
      type: object
      properties:
        dataRecordId:
          type: string
    ProcessedRecord:
      type: object
      properties:
        dataRecordId:
          type: string
        name:
          type: string
        phoneNumber:
          type: string
        amount:
          type: number
          format: decimal
        createTime:
          type: string
          format: date-time
    GetDataRecordReport:
      type: object
      properties:
        entries:
          type: array
          items:
            $ref: '#/components/schemas/GetDataRecordReportEntry'
    GetDataRecordReportEntry:
      type: object
      properties:
        phoneNumber:
          type: string
        records:
          type: array
          items:
            $ref: '#/components/schemas/RecordData'
    RecordData:
      type: object
      properties:
        name:
          type: string
        content:
          $ref: '#/components/schemas/Content'
    Content:
      type: object
      properties:
        amountsSum:
          type: number
          format: decimal
        newestRecordCreateDate:
          type: string
          format: date
    UpdateProcessConfigRequest:
      type: object
      properties:
        prioritiesByAmount:
          type: array
          items:
            $ref: '#/components/schemas/PriorityByAmountConfig'
    GetProcessConfigResponse:
      type: object
      properties:
        prioritiesByAmount:
          type: array
          items:
            $ref: '#/components/schemas/PriorityByAmountConfig'
    PriorityByAmountConfig:
      type: object
      properties:
        from:
          type: number
          format: decimal
        to:
          type: number
          format: decimal
          nullable: true
        priority:
          type: integer
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string